### PR TITLE
Update for Arduino Due support

### PR DESCRIPTION
**Pull request by panamajoecu**
Updated your awesome FIFO code to support the Arduino Due

### CODE REVIEW

**Comment by wizard97** [comment]
Awesome work, thanks for the pull request!

Quickly looking over your pull request, I believe this might already be implemented in the [dev branch](https://github.com/wizard97/ArduinoRingBuffer/tree/dev) which uses this [SimplyAtomic](https://github.com/wizard97/SimplyAtomic) lib for handling saving a restoring interrupts. 

Please take a look, and let me know if I am mistaken.

**Comment by panamajoecu** [comment]
You're right!  It was a drop in replacement for my Sam3 code.  

Had put this together back in December, just hadn't gotten around to uploading.  You beat me to it!  Seems to be working well.  Maybe it deserves to be in the main branch?

**Comment by wizard97** [comment]
Should of pushed it in December and saved me the trouble! 

I plan to replace master with it at some point, but I am yet to have been able to test it on most of the platforms it is supposed to support, glad to hear it is working correctly on ARM.

**Comment by panamajoecu** [comment]
Haha.  Yep.  Procrastination is one of my weaknesses...

I'll see if I can write a test case for you on AVR in the next month or two.  If you don't see anything by then, send a message as a reminder!

**Comment by wizard97** [comment]
Same here...

That would be fantastic, thanks!

**Pull request closed without merging**
